/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Bostad API
 * OpenAPI spec version: 0.1.0
 */
import type { Listing } from './listing';
import type { ListingParseError } from './listingParseError';
import type { AllListingsResponseLoggedIn } from './allListingsResponseLoggedIn';

export interface AllListingsResponse {
  listings: Listing[];
  errors: ListingParseError[];
  loggedIn?: AllListingsResponseLoggedIn;
}
