/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Bostad API
 * OpenAPI spec version: 0.1.0
 */
import type { AllocationInfoAllocationMethod } from './allocationInfoAllocationMethod';
import type { AllocationInfoMyPosition } from './allocationInfoMyPosition';
import type { AllocationInfoTotal } from './allocationInfoTotal';
import type { AllocationInfoOldestQueueDates } from './allocationInfoOldestQueueDates';
import type { AllocationInfoHasGoodChance } from './allocationInfoHasGoodChance';

export interface AllocationInfo {
  allocationMethod?: AllocationInfoAllocationMethod;
  myPosition?: AllocationInfoMyPosition;
  total?: AllocationInfoTotal;
  oldestQueueDates?: AllocationInfoOldestQueueDates;
  hasGoodChance?: AllocationInfoHasGoodChance;
}
