/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Bostad API
 * OpenAPI spec version: 0.1.0
 */

export type AllocationMethod = typeof AllocationMethod[keyof typeof AllocationMethod];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AllocationMethod = {
  queue_points: 'queue_points',
  random: 'random',
  application_date: 'application_date',
  manual_request: 'manual_request',
  unknown: 'unknown',
} as const;
