/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Bostad API
 * OpenAPI spec version: 0.1.0
 */
import type { BostadSthlmSearchOptionsMaxListings } from './bostadSthlmSearchOptionsMaxListings';
import type { BostadSthlmSearchOptionsCookie } from './bostadSthlmSearchOptionsCookie';

/**
 * Source-specific search options for bostad.stockholm.se.
 */
export interface BostadSthlmSearchOptions {
  maxListings?: BostadSthlmSearchOptionsMaxListings;
  cookie?: BostadSthlmSearchOptionsCookie;
}
