/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Bostad API
 * OpenAPI spec version: 0.1.0
 */
import type { DateRangeMin } from './dateRangeMin';
import type { DateRangeMax } from './dateRangeMax';

export interface DateRange {
  min?: DateRangeMin;
  max?: DateRangeMax;
}
