/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Bostad API
 * OpenAPI spec version: 0.1.0
 */
import type { ListingFeaturesBalcony } from './listingFeaturesBalcony';
import type { ListingFeaturesElevator } from './listingFeaturesElevator';
import type { ListingFeaturesNewProduction } from './listingFeaturesNewProduction';
import type { ListingFeaturesKitchen } from './listingFeaturesKitchen';
import type { ListingFeaturesBathroom } from './listingFeaturesBathroom';
import type { ListingFeaturesHasViewing } from './listingFeaturesHasViewing';

export interface ListingFeatures {
  balcony?: ListingFeaturesBalcony;
  elevator?: ListingFeaturesElevator;
  newProduction?: ListingFeaturesNewProduction;
  kitchen?: ListingFeaturesKitchen;
  bathroom?: ListingFeaturesBathroom;
  dishwasher?: boolean;
  washingMachine?: boolean;
  dryer?: boolean;
  hasViewing?: ListingFeaturesHasViewing;
  hasPictures?: boolean;
  hasFloorplan?: boolean;
}
