/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Bostad API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Supported listing source identifiers shared across the API.
 */
export type ListingSources = typeof ListingSources[keyof typeof ListingSources];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListingSources = {
  bostadsthlm: 'bostadsthlm',
  homeq: 'homeq',
} as const;
