/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Bostad API
 * OpenAPI spec version: 0.1.0
 */
import type { ListingSources } from './listingSources';
import type { ListingParseErrorUrl } from './listingParseErrorUrl';

export interface ListingParseError {
  id: string;
  source: ListingSources;
  sourceLocalId: string;
  url?: ListingParseErrorUrl;
  reason: string;
}
