/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Bostad API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Typed search options for listing fetch requests.

The API accepts a list to be forward-compatible with multi-source scraping,
but currently only the single source "bostadsthlm" is supported.
 */
export interface ListingsSearchOptions {
  sources?: 'bostadsthlm'[];
}
