/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Bostad API
 * OpenAPI spec version: 0.1.0
 */

export type ListingApartmentType = typeof ListingApartmentType[keyof typeof ListingApartmentType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListingApartmentType = {
  regular: 'regular',
  youth: 'youth',
  student: 'student',
  senior: 'senior',
} as const;
