/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Bostad API
 * OpenAPI spec version: 0.1.0
 */
import type { ListingSources } from './listingSources';
import type { ListingsSearchOptionsMaxListings } from './listingsSearchOptionsMaxListings';
import type { ListingsSearchOptionsCookie } from './listingsSearchOptionsCookie';

/**
 * Typed search options for listing fetch requests.

The API accepts a list to be forward-compatible with multi-source scraping,
but currently only one built-in source is supported.

`max_listings` can be used during debugging to parse only the first N
listing index items. It defaults to None, which parses all listings.
 */
export interface ListingsSearchOptions {
  sources?: ListingSources[];
  maxListings?: ListingsSearchOptionsMaxListings;
  cookie?: ListingsSearchOptionsCookie;
}
