/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Bostad API
 * OpenAPI spec version: 0.1.0
 */
import type { ListingSources } from './listingSources';
import type { ListingsSearchOptionsBostadsthlm } from './listingsSearchOptionsBostadsthlm';
import type { ListingsSearchOptionsHomeq } from './listingsSearchOptionsHomeq';

/**
 * Typed search options for listing fetch requests.

`sources` selects which sources to scrape in one combined request, while
each source can expose its own nested option object.
 */
export interface ListingsSearchOptions {
  sources?: ListingSources[];
  bostadsthlm?: ListingsSearchOptionsBostadsthlm;
  homeq?: ListingsSearchOptionsHomeq;
}
