/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Bostad API
 * OpenAPI spec version: 0.1.0
 */
import type { ListingSources } from './listingSources';
import type { ListingApartmentType } from './listingApartmentType';
import type { ListingFeatures } from './listingFeatures';
import type { ListingFloor } from './listingFloor';
import type { ListingRentalPeriod } from './listingRentalPeriod';
import type { ListingCoords } from './listingCoords';
import type { ListingApplicationDeadline } from './listingApplicationDeadline';
import type { ListingQueuePosition } from './listingQueuePosition';
import type { ListingRequirements } from './listingRequirements';
import type { ListingDatePosted } from './listingDatePosted';
import type { ListingImageUrls } from './listingImageUrls';
import type { ListingFloorplanUrl } from './listingFloorplanUrl';
import type { ListingFreeText } from './listingFreeText';
import type { ListingDistrictId } from './listingDistrictId';
import type { ListingNumApartments } from './listingNumApartments';
import type { ListingRentRange } from './listingRentRange';
import type { ListingAreaSqmRange } from './listingAreaSqmRange';
import type { ListingFloorRange } from './listingFloorRange';

export interface Listing {
  id: string;
  source: ListingSources;
  sourceLocalId: string;
  url: string;
  name: string;
  locMunicipality: string;
  locDistrict: string;
  rent: number;
  areaSqm: number;
  numRooms: number;
  apartmentType: ListingApartmentType;
  features?: ListingFeatures;
  floor: ListingFloor;
  rentalPeriod?: ListingRentalPeriod;
  coords?: ListingCoords;
  applicationDeadline?: ListingApplicationDeadline;
  queuePosition?: ListingQueuePosition;
  requirements?: ListingRequirements;
  datePosted?: ListingDatePosted;
  imageUrls?: ListingImageUrls;
  floorplanUrl?: ListingFloorplanUrl;
  freeText?: ListingFreeText;
  districtId?: ListingDistrictId;
  numApartments?: ListingNumApartments;
  rentRange?: ListingRentRange;
  areaSqmRange?: ListingAreaSqmRange;
  floorRange?: ListingFloorRange;
}
