/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Bostad API
 * OpenAPI spec version: 0.1.0
 */
import type { QueuePositionMyPosition } from './queuePositionMyPosition';
import type { QueuePositionTotal } from './queuePositionTotal';
import type { QueuePositionQueueTimesSorted } from './queuePositionQueueTimesSorted';
import type { QueuePositionHasGoodChance } from './queuePositionHasGoodChance';

export interface QueuePosition {
  myPosition?: QueuePositionMyPosition;
  total?: QueuePositionTotal;
  queueTimesSorted?: QueuePositionQueueTimesSorted;
  hasGoodChance?: QueuePositionHasGoodChance;
}
