/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Bostad API
 * OpenAPI spec version: 0.1.0
 */
import type { QueueStatusMyPosition } from './queueStatusMyPosition';
import type { QueueStatusTotal } from './queueStatusTotal';
import type { QueueStatusOldestQueueDates } from './queueStatusOldestQueueDates';
import type { QueueStatusHasGoodChance } from './queueStatusHasGoodChance';
import type { QueueStatusAllocationMethod } from './queueStatusAllocationMethod';

export interface QueueStatus {
  myPosition?: QueueStatusMyPosition;
  total?: QueueStatusTotal;
  oldestQueueDates?: QueueStatusOldestQueueDates;
  hasGoodChance?: QueueStatusHasGoodChance;
  allocationMethod?: QueueStatusAllocationMethod;
}
