/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Bostad API
 * OpenAPI spec version: 0.1.0
 */
import type { RangeMin } from './rangeMin';
import type { RangeMax } from './rangeMax';

export interface Range {
  min?: RangeMin;
  max?: RangeMax;
}
