/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Bostad API
 * OpenAPI spec version: 0.1.0
 */
import type { TenantRequirementsAgeRange } from './tenantRequirementsAgeRange';
import type { TenantRequirementsIncomeRange } from './tenantRequirementsIncomeRange';
import type { TenantRequirementsNumTenantsRange } from './tenantRequirementsNumTenantsRange';

export interface TenantRequirements {
  student: boolean;
  ageRange?: TenantRequirementsAgeRange;
  incomeRange?: TenantRequirementsIncomeRange;
  numTenantsRange?: TenantRequirementsNumTenantsRange;
}
