/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Bostad API
 * OpenAPI spec version: 0.1.0
 */

export type TenureType = typeof TenureType[keyof typeof TenureType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TenureType = {
  first_hand: 'first_hand',
  second_hand_private: 'second_hand_private',
  second_hand_shared: 'second_hand_shared',
} as const;
