/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Bostad API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AllListingsResponse,
  HTTPValidationError,
  ListingsSearchOptions
} from '.././models';


type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




/**
 * @summary All Listings
 */
export type allListingsApiAllListingsGetResponse200 = {
  data: AllListingsResponse
  status: 200
}
    
export type allListingsApiAllListingsGetResponseSuccess = (allListingsApiAllListingsGetResponse200) & {
  headers: Headers;
};
;

export type allListingsApiAllListingsGetResponse = (allListingsApiAllListingsGetResponseSuccess)

export const getAllListingsApiAllListingsGetUrl = () => {


  

  return `/api/all_listings`
}

export const allListingsApiAllListingsGet = async ( options?: RequestInit): Promise<allListingsApiAllListingsGetResponse> => {
  
  const res = await fetch(getAllListingsApiAllListingsGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: allListingsApiAllListingsGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as allListingsApiAllListingsGetResponse
}





export const getAllListingsApiAllListingsGetQueryKey = () => {
    return [
    `/api/all_listings`
    ] as const;
    }

    
export const getAllListingsApiAllListingsGetQueryOptions = <TData = Awaited<ReturnType<typeof allListingsApiAllListingsGet>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof allListingsApiAllListingsGet>>, TError, TData>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAllListingsApiAllListingsGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof allListingsApiAllListingsGet>>> = ({ signal }) => allListingsApiAllListingsGet({ signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof allListingsApiAllListingsGet>>, TError, TData> & { queryKey: QueryKey }
}

export type AllListingsApiAllListingsGetQueryResult = NonNullable<Awaited<ReturnType<typeof allListingsApiAllListingsGet>>>
export type AllListingsApiAllListingsGetQueryError = unknown


/**
 * @summary All Listings
 */

export function useAllListingsApiAllListingsGet<TData = Awaited<ReturnType<typeof allListingsApiAllListingsGet>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof allListingsApiAllListingsGet>>, TError, TData>, fetch?: RequestInit}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getAllListingsApiAllListingsGetQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary All Listings Post
 */
export type allListingsPostApiAllListingsPostResponse200 = {
  data: AllListingsResponse
  status: 200
}

export type allListingsPostApiAllListingsPostResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type allListingsPostApiAllListingsPostResponseSuccess = (allListingsPostApiAllListingsPostResponse200) & {
  headers: Headers;
};
export type allListingsPostApiAllListingsPostResponseError = (allListingsPostApiAllListingsPostResponse422) & {
  headers: Headers;
};

export type allListingsPostApiAllListingsPostResponse = (allListingsPostApiAllListingsPostResponseSuccess | allListingsPostApiAllListingsPostResponseError)

export const getAllListingsPostApiAllListingsPostUrl = () => {


  

  return `/api/all_listings`
}

export const allListingsPostApiAllListingsPost = async (listingsSearchOptions: ListingsSearchOptions, options?: RequestInit): Promise<allListingsPostApiAllListingsPostResponse> => {
  
  const res = await fetch(getAllListingsPostApiAllListingsPostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      listingsSearchOptions,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: allListingsPostApiAllListingsPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as allListingsPostApiAllListingsPostResponse
}




export const getAllListingsPostApiAllListingsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof allListingsPostApiAllListingsPost>>, TError,{data: ListingsSearchOptions}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof allListingsPostApiAllListingsPost>>, TError,{data: ListingsSearchOptions}, TContext> => {

const mutationKey = ['allListingsPostApiAllListingsPost'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof allListingsPostApiAllListingsPost>>, {data: ListingsSearchOptions}> = (props) => {
          const {data} = props ?? {};

          return  allListingsPostApiAllListingsPost(data,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AllListingsPostApiAllListingsPostMutationResult = NonNullable<Awaited<ReturnType<typeof allListingsPostApiAllListingsPost>>>
    export type AllListingsPostApiAllListingsPostMutationBody = ListingsSearchOptions
    export type AllListingsPostApiAllListingsPostMutationError = HTTPValidationError

    /**
 * @summary All Listings Post
 */
export const useAllListingsPostApiAllListingsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof allListingsPostApiAllListingsPost>>, TError,{data: ListingsSearchOptions}, TContext>, fetch?: RequestInit}
 ): UseMutationResult<
        Awaited<ReturnType<typeof allListingsPostApiAllListingsPost>>,
        TError,
        {data: ListingsSearchOptions},
        TContext
      > => {

      const mutationOptions = getAllListingsPostApiAllListingsPostMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary All Listings Stream
 */
export type allListingsStreamApiAllListingsStreamGetResponse200 = {
  data: unknown
  status: 200
}
    
export type allListingsStreamApiAllListingsStreamGetResponseSuccess = (allListingsStreamApiAllListingsStreamGetResponse200) & {
  headers: Headers;
};
;

export type allListingsStreamApiAllListingsStreamGetResponse = (allListingsStreamApiAllListingsStreamGetResponseSuccess)

export const getAllListingsStreamApiAllListingsStreamGetUrl = () => {


  

  return `/api/all_listings/stream`
}

export const allListingsStreamApiAllListingsStreamGet = async ( options?: RequestInit): Promise<allListingsStreamApiAllListingsStreamGetResponse> => {
  
  const res = await fetch(getAllListingsStreamApiAllListingsStreamGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: allListingsStreamApiAllListingsStreamGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as allListingsStreamApiAllListingsStreamGetResponse
}





export const getAllListingsStreamApiAllListingsStreamGetQueryKey = () => {
    return [
    `/api/all_listings/stream`
    ] as const;
    }

    
export const getAllListingsStreamApiAllListingsStreamGetQueryOptions = <TData = Awaited<ReturnType<typeof allListingsStreamApiAllListingsStreamGet>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof allListingsStreamApiAllListingsStreamGet>>, TError, TData>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAllListingsStreamApiAllListingsStreamGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof allListingsStreamApiAllListingsStreamGet>>> = ({ signal }) => allListingsStreamApiAllListingsStreamGet({ signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof allListingsStreamApiAllListingsStreamGet>>, TError, TData> & { queryKey: QueryKey }
}

export type AllListingsStreamApiAllListingsStreamGetQueryResult = NonNullable<Awaited<ReturnType<typeof allListingsStreamApiAllListingsStreamGet>>>
export type AllListingsStreamApiAllListingsStreamGetQueryError = unknown


/**
 * @summary All Listings Stream
 */

export function useAllListingsStreamApiAllListingsStreamGet<TData = Awaited<ReturnType<typeof allListingsStreamApiAllListingsStreamGet>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof allListingsStreamApiAllListingsStreamGet>>, TError, TData>, fetch?: RequestInit}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getAllListingsStreamApiAllListingsStreamGetQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary All Listings Stream Post
 */
export type allListingsStreamPostApiAllListingsStreamPostResponse200 = {
  data: unknown
  status: 200
}

export type allListingsStreamPostApiAllListingsStreamPostResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type allListingsStreamPostApiAllListingsStreamPostResponseSuccess = (allListingsStreamPostApiAllListingsStreamPostResponse200) & {
  headers: Headers;
};
export type allListingsStreamPostApiAllListingsStreamPostResponseError = (allListingsStreamPostApiAllListingsStreamPostResponse422) & {
  headers: Headers;
};

export type allListingsStreamPostApiAllListingsStreamPostResponse = (allListingsStreamPostApiAllListingsStreamPostResponseSuccess | allListingsStreamPostApiAllListingsStreamPostResponseError)

export const getAllListingsStreamPostApiAllListingsStreamPostUrl = () => {


  

  return `/api/all_listings/stream`
}

export const allListingsStreamPostApiAllListingsStreamPost = async (listingsSearchOptions: ListingsSearchOptions, options?: RequestInit): Promise<allListingsStreamPostApiAllListingsStreamPostResponse> => {
  
  const res = await fetch(getAllListingsStreamPostApiAllListingsStreamPostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      listingsSearchOptions,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: allListingsStreamPostApiAllListingsStreamPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as allListingsStreamPostApiAllListingsStreamPostResponse
}




export const getAllListingsStreamPostApiAllListingsStreamPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof allListingsStreamPostApiAllListingsStreamPost>>, TError,{data: ListingsSearchOptions}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof allListingsStreamPostApiAllListingsStreamPost>>, TError,{data: ListingsSearchOptions}, TContext> => {

const mutationKey = ['allListingsStreamPostApiAllListingsStreamPost'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof allListingsStreamPostApiAllListingsStreamPost>>, {data: ListingsSearchOptions}> = (props) => {
          const {data} = props ?? {};

          return  allListingsStreamPostApiAllListingsStreamPost(data,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AllListingsStreamPostApiAllListingsStreamPostMutationResult = NonNullable<Awaited<ReturnType<typeof allListingsStreamPostApiAllListingsStreamPost>>>
    export type AllListingsStreamPostApiAllListingsStreamPostMutationBody = ListingsSearchOptions
    export type AllListingsStreamPostApiAllListingsStreamPostMutationError = HTTPValidationError

    /**
 * @summary All Listings Stream Post
 */
export const useAllListingsStreamPostApiAllListingsStreamPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof allListingsStreamPostApiAllListingsStreamPost>>, TError,{data: ListingsSearchOptions}, TContext>, fetch?: RequestInit}
 ): UseMutationResult<
        Awaited<ReturnType<typeof allListingsStreamPostApiAllListingsStreamPost>>,
        TError,
        {data: ListingsSearchOptions},
        TContext
      > => {

      const mutationOptions = getAllListingsStreamPostApiAllListingsStreamPostMutationOptions(options);

      return useMutation(mutationOptions);
    }
    