/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Bostad API
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AllListingsResponse
} from '.././models';





/**
 * @summary All Listings
 */
export type allListingsApiAllListingsGetResponse200 = {
  data: AllListingsResponse
  status: 200
}
    
export type allListingsApiAllListingsGetResponseSuccess = (allListingsApiAllListingsGetResponse200) & {
  headers: Headers;
};
;

export type allListingsApiAllListingsGetResponse = (allListingsApiAllListingsGetResponseSuccess)

export const getAllListingsApiAllListingsGetUrl = () => {


  

  return `/api/all_listings`
}

export const allListingsApiAllListingsGet = async ( options?: RequestInit): Promise<allListingsApiAllListingsGetResponse> => {
  
  const res = await fetch(getAllListingsApiAllListingsGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: allListingsApiAllListingsGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as allListingsApiAllListingsGetResponse
}





export const getAllListingsApiAllListingsGetQueryKey = () => {
    return [
    `/api/all_listings`
    ] as const;
    }

    
export const getAllListingsApiAllListingsGetQueryOptions = <TData = Awaited<ReturnType<typeof allListingsApiAllListingsGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof allListingsApiAllListingsGet>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAllListingsApiAllListingsGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof allListingsApiAllListingsGet>>> = ({ signal }) => allListingsApiAllListingsGet({ signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof allListingsApiAllListingsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AllListingsApiAllListingsGetQueryResult = NonNullable<Awaited<ReturnType<typeof allListingsApiAllListingsGet>>>
export type AllListingsApiAllListingsGetQueryError = unknown


export function useAllListingsApiAllListingsGet<TData = Awaited<ReturnType<typeof allListingsApiAllListingsGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof allListingsApiAllListingsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof allListingsApiAllListingsGet>>,
          TError,
          Awaited<ReturnType<typeof allListingsApiAllListingsGet>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAllListingsApiAllListingsGet<TData = Awaited<ReturnType<typeof allListingsApiAllListingsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof allListingsApiAllListingsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof allListingsApiAllListingsGet>>,
          TError,
          Awaited<ReturnType<typeof allListingsApiAllListingsGet>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAllListingsApiAllListingsGet<TData = Awaited<ReturnType<typeof allListingsApiAllListingsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof allListingsApiAllListingsGet>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary All Listings
 */

export function useAllListingsApiAllListingsGet<TData = Awaited<ReturnType<typeof allListingsApiAllListingsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof allListingsApiAllListingsGet>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAllListingsApiAllListingsGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




